#!/usr/bin/env python3
"""Draw the application icon and write it out as PNG and ICO.

The `assets/icon*.png` files and `assets/icon.ico` are generated by this script,
which is kept beside them so the binaries have a provenance: the icon is a shape
described in code, not a bitmap someone would have to redraw by hand. It uses
only the standard library, so it runs anywhere Python does — there is no Pillow
on the machine this was written on.

    python3 assets/make-icon.py

The icon is a rounded square on an indigo-to-violet gradient, carrying the
Markdown mark — an M beside a downward arrow — in white.

Every shape is evaluated as a signed distance and rasterised from that, so each
size is drawn at its own resolution and the small ICO entries are as sharp as
the large one; they are not downsampled from the 1024. A distance of `d` from a
shape's edge becomes coverage `0.5 - d`, which is the standard way to antialias
a distance field: pixels straddling the edge land between 0 and 1, and anything
further than half a pixel away is fully in or fully out.
"""

import math
import struct
import zlib
from pathlib import Path

# The design is laid out once, in a 1024x1024 space, and scaled to whatever size
# is being drawn. Every number below is a coordinate in that space.
DESIGN = 1024.0

# The rounded square, inset from the canvas edge so the gradient has a moment to
# breathe and the corners do not touch the icon's own bounds.
MARGIN = 56.0

# The Markdown mark. `STROKE` is the width of every stroke in it, so the two
# halves of the figure share one weight.
STROKE = 76.0
M_LEFT = 232.0
M_RIGHT = 492.0
M_TOP = 340.0
M_BOTTOM = 664.0
M_APEX = 512.0
ARROW_X = 712.0
ARROW_SHOULDER = 570.0  # where the shaft meets the head
ARROW_TIP = 680.0
HEAD_HALF = 84.0
HEAD_TOP = 566.0

# Top and bottom of the background gradient, as sRGB bytes.
GRADIENT_TOP = (79, 70, 229)  # indigo
GRADIENT_BOTTOM = (139, 60, 240)  # violet
FOREGROUND = (255, 255, 255)

# Below this many pixels, the full mark is drawn as just the arrow, larger and
# heavier. The M is four strokes in a six-pixel box at 16px, and at that size it
# is a smudge however it is rasterised — the arrow alone still reads.
SIMPLE_BELOW = 40.0

# The arrow, redrawn to fill the tile on its own.
SIMPLE_STROKE = 124.0
SIMPLE_SHAFT_TOP = 330.0
SIMPLE_SHOULDER = 552.0
SIMPLE_TIP = 704.0
SIMPLE_HEAD_HALF = 152.0
SIMPLE_HEAD_TOP = 540.0

# The sizes an ICO carries. Windows picks the one it needs for each context —
# 16 for the title bar, 32 for the taskbar, 256 for large thumbnails.
ICO_SIZES = (16, 32, 48, 64, 128, 256)

# The PNGs written for the packagers to install. These are the sizes an `.icns`
# is able to hold: 16, 32, 48, 64, 128, 256 and 512 at 1x — and 1024 only as 512
# at 2x, which is why exactly one file carries a `@2x` name. That suffix is how
# the density is communicated to the packager, not a note about the file, and a
# 1024 named without it is refused: there is no ICNS entry to put it in.
#
# Each size is drawn at its own resolution rather than downsampled, which is
# what `SIMPLE_BELOW` is for — the small entries are the ones that need the
# simpler mark, and they only get it if they are rasterised here.
PNG_OUTPUTS = (
    (16, "icon-16.png"),
    (32, "icon-32.png"),
    (128, "icon-128.png"),
    (256, "icon-256.png"),
    (512, "icon.png"),
    (1024, "icon@2x.png"),
)


def sd_rounded_rect(px, py, cx, cy, half_w, half_h, radius):
    """Signed distance to a rounded rectangle: negative inside."""
    qx = abs(px - cx) - (half_w - radius)
    qy = abs(py - cy) - (half_h - radius)
    return (
        math.hypot(max(qx, 0.0), max(qy, 0.0))
        + min(max(qx, qy), 0.0)
        - radius
    )


def sd_segment(px, py, ax, ay, bx, by):
    """Distance to the segment ab, ignoring any thickness."""
    vx, vy = bx - ax, by - ay
    wx, wy = px - ax, py - ay
    length_squared = vx * vx + vy * vy
    t = (
        0.0
        if length_squared == 0.0
        else max(0.0, min(1.0, (wx * vx + wy * vy) / length_squared))
    )
    return math.hypot(wx - t * vx, wy - t * vy)


def sd_triangle(px, py, a, b, c):
    """Signed distance to triangle abc, negative inside.

    Exact rather than approximate because the triangle is convex, which is the
    case where "nearest edge, signed by which side you are on" is the true
    distance.
    """
    distance = min(
        sd_segment(px, py, *a, *b),
        sd_segment(px, py, *b, *c),
        sd_segment(px, py, *c, *a),
    )
    inside = True
    for start, end in ((a, b), (b, c), (c, a)):
        cross = (end[0] - start[0]) * (py - start[1]) - (end[1] - start[1]) * (
            px - start[0]
        )
        if cross < 0.0:
            inside = False
            break
    return -distance if inside else distance


def mark_distance(px, py, simple):
    """Signed distance to the whole Markdown mark, negative inside.

    The mark is the union of its strokes, and the union of a set of shapes is
    the minimum of their distances.

    `simple` draws the arrow on its own, scaled up, for sizes too small to carry
    both halves of the figure.
    """
    if simple:
        half = SIMPLE_STROKE / 2.0
        return min(
            sd_segment(px, py, 512.0, SIMPLE_SHAFT_TOP, 512.0, SIMPLE_SHOULDER) - half,
            sd_triangle(
                px,
                py,
                (512.0, SIMPLE_TIP),
                (512.0 - SIMPLE_HEAD_HALF, SIMPLE_HEAD_TOP),
                (512.0 + SIMPLE_HEAD_HALF, SIMPLE_HEAD_TOP),
            ),
        )

    half = STROKE / 2.0
    strokes = [
        # The M: two uprights and two diagonals meeting at the apex.
        sd_segment(px, py, M_LEFT, M_TOP, M_LEFT, M_BOTTOM) - half,
        sd_segment(px, py, M_RIGHT, M_TOP, M_RIGHT, M_BOTTOM) - half,
        sd_segment(px, py, M_LEFT, M_TOP, (M_LEFT + M_RIGHT) / 2, M_APEX) - half,
        sd_segment(
            px, py, (M_LEFT + M_RIGHT) / 2, M_APEX, M_RIGHT, M_TOP
        )
        - half,
        # The arrow: a shaft with a triangular head.
        sd_segment(px, py, ARROW_X, M_TOP, ARROW_X, ARROW_SHOULDER) - half,
        sd_triangle(
            px,
            py,
            (ARROW_X, ARROW_TIP),
            (ARROW_X - HEAD_HALF, HEAD_TOP),
            (ARROW_X + HEAD_HALF, HEAD_TOP),
        ),
    ]
    return min(strokes)


def coverage(distance):
    """How much of a pixel the shape covers, given its distance from the edge."""
    return max(0.0, min(1.0, 0.5 - distance))


def render(size):
    """One size of the icon as straight (non-premultiplied) RGBA bytes."""
    scale = size / DESIGN
    center = size / 2.0
    half = (DESIGN - 2.0 * MARGIN) / 2.0 * scale
    radius = 0.225 * DESIGN * scale  # Big Sur's corner radius, near enough
    simple = size < SIMPLE_BELOW

    pixels = bytearray()
    for y in range(size):
        # Sample at the pixel's center.
        dy = y + 0.5
        for x in range(size):
            dx = x + 0.5

            background = coverage(
                sd_rounded_rect(dx, dy, center, center, half, half, radius)
            )
            foreground = (
                coverage(mark_distance(dx / scale, dy / scale, simple))
                if background > 0.0
                else 0.0
            )

            alpha = foreground + background * (1.0 - foreground)
            if alpha <= 0.0:
                pixels += b"\x00\x00\x00\x00"
                continue

            # The gradient runs top to bottom, and is composited under the mark.
            mix = dy / size
            tint = [
                GRADIENT_TOP[i] + (GRADIENT_BOTTOM[i] - GRADIENT_TOP[i]) * mix
                for i in range(3)
            ]
            # Un-premultiply: the stored colour is what the pixel looks like
            # once it is composited over whatever is behind the icon.
            colour = [
                (FOREGROUND[i] * foreground + tint[i] * background * (1.0 - foreground))
                / alpha
                for i in range(3)
            ]
            pixels += bytes(
                [round(min(255.0, c)) for c in colour] + [round(alpha * 255.0)]
            )
    return pixels


def png_bytes(size, pixels):
    """A complete PNG file, as bytes."""
    raw = bytearray()
    stride = size * 4
    for y in range(size):
        # Filter type 0 (None) for every scanline. The image is smooth, so a
        # smarter filter would buy little and cost a dependency-free
        # implementation its simplicity.
        raw.append(0)
        raw += pixels[y * stride : (y + 1) * stride]

    def chunk(tag, data):
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    return (
        b"\x89PNG\r\n\x1a\n"
        # 8-bit depth, colour type 6 (RGBA), no interlacing.
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def write_ico(path, images):
    """An ICO holding `images`, a list of (size, PNG bytes).

    Windows has accepted PNG-compressed entries since Vista, which is well
    below the version this app runs on, so every entry is stored as PNG rather
    than as the older uncompressed DIB.
    """
    header = struct.pack("<HHH", 0, 1, len(images))

    # The directory entries come first and each one records where its image
    # starts, so the offsets depend on how many entries there are.
    offset = len(header) + 16 * len(images)
    entries = bytearray()
    data = bytearray()
    for size, png in images:
        # A dimension of 256 does not fit in the byte the format gives it, so
        # zero is how the format spells it.
        dimension = 0 if size >= 256 else size
        entries += struct.pack(
            "<BBBBHHII", dimension, dimension, 0, 0, 1, 32, len(png), offset
        )
        offset += len(png)
        data += png

    path.write_bytes(bytes(header + entries + data))


def main():
    here = Path(__file__).resolve().parent

    for size, name in PNG_OUTPUTS:
        (here / name).write_bytes(png_bytes(size, render(size)))
        print(f"wrote {here / name} ({size}x{size})")

    images = [(size, png_bytes(size, render(size))) for size in ICO_SIZES]
    write_ico(here / "icon.ico", images)
    print(f"wrote {here / 'icon.ico'} ({', '.join(str(s) for s in ICO_SIZES)})")


if __name__ == "__main__":
    main()
